import {
  Building2,
  Calculator,
  Crown,
  DollarSign,
  Laptop,
  Leaf,
  Network,
  Scale,
  TrendingUp,
  Users,
} from 'lucide-react';

import type {
  Seminar,
  SeminarCategoryInfo,
  SeminarSeries,
  Speaker,
} from '@/types/seminar';

export const SEMINAR_CATEGORIES: SeminarCategoryInfo[] = [
  {
    key: 'leadership',
    name: '리더십 & 경영',
    description: '차세대 리더를 위한 경영 전략과 리더십 개발',
    icon: Crown,
    color: 'text-purple-700 dark:text-purple-300',
    bgColor:
      'bg-purple-100 dark:bg-purple-900/30 border border-purple-200 dark:border-purple-800',
  },
  {
    key: 'finance',
    name: '금융 & 자산관리',
    description: '체계적인 자산관리와 포트폴리오 최적화 전략',
    icon: TrendingUp,
    color: 'text-blue-700 dark:text-blue-300',
    bgColor:
      'bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-800',
  },
  {
    key: 'legal',
    name: '법무 & 컴플라이언스',
    description: '기업 법무 실무와 최신 규제 대응 방안',
    icon: Scale,
    color: 'text-green-700 dark:text-green-300',
    bgColor:
      'bg-green-100 dark:bg-green-900/30 border border-green-200 dark:border-green-800',
  },
  {
    key: 'succession',
    name: '가업승계',
    description: '체계적인 가업승계 설계와 실행 전략',
    icon: Users,
    color: 'text-orange-700 dark:text-orange-300',
    bgColor:
      'bg-orange-100 dark:bg-orange-900/30 border border-orange-200 dark:border-orange-800',
  },
  {
    key: 'investment',
    name: '투자 전략',
    description: '프라이빗 투자와 대체투자 기회 분석',
    icon: DollarSign,
    color: 'text-emerald-700 dark:text-emerald-300',
    bgColor:
      'bg-emerald-100 dark:bg-emerald-900/30 border border-emerald-200 dark:border-emerald-800',
  },
  {
    key: 'taxation',
    name: '세무 & 절세',
    description: '최신 세법 변화와 효과적인 절세 전략',
    icon: Calculator,
    color: 'text-red-700 dark:text-red-300',
    bgColor:
      'bg-red-100 dark:bg-red-900/30 border border-red-200 dark:border-red-800',
  },
  {
    key: 'management',
    name: '경영 혁신',
    description: '디지털 전환과 경영 혁신 사례 분석',
    icon: Building2,
    color: 'text-indigo-700 dark:text-indigo-300',
    bgColor:
      'bg-indigo-100 dark:bg-indigo-900/30 border border-indigo-200 dark:border-indigo-800',
  },
  {
    key: 'networking',
    name: '네트워킹',
    description: '동종업계 리더들과의 교류와 정보 공유',
    icon: Network,
    color: 'text-pink-700 dark:text-pink-300',
    bgColor:
      'bg-pink-100 dark:bg-pink-900/30 border border-pink-200 dark:border-pink-800',
  },
  {
    key: 'technology',
    name: '기술 & 혁신',
    description: '최신 기술 트렌드와 혁신 사례 연구',
    icon: Laptop,
    color: 'text-cyan-700 dark:text-cyan-300',
    bgColor:
      'bg-cyan-100 dark:bg-cyan-900/30 border border-cyan-200 dark:border-cyan-800',
  },
  {
    key: 'esg',
    name: 'ESG & 지속가능경영',
    description: 'ESG 경영과 지속가능한 성장 전략',
    icon: Leaf,
    color: 'text-teal-700 dark:text-teal-300',
    bgColor:
      'bg-teal-100 dark:bg-teal-900/30 border border-teal-200 dark:border-teal-800',
  },
];

// 새로운 강연자 정보 추가
export const SPEAKERS = {
  leeSangSun: {
    id: 'lee-sang-sun',
    name: '이상선',
    title: '박사',
    company: '삼성생명 컨설턴트',
    bio: '삼성생명에서 패밀리오피스 분야의 전문가로 20년 이상의 경험을 보유하고 있으며, 가업승계와 자산관리 전략의 권위자입니다.',
    expertise: ['가업승계', '자산관리', '패밀리오피스', '경영전략'],
  },
  hwangByungHoon: {
    id: 'hwang-byung-hoon',
    name: '황병훈',
    title: '세무전문가',
    company: '삼성패밀리오피스',
    bio: '삼성패밀리오피스 소속 세무전문가로 고액자산가 세무 전문가로 15년 이상의 경험을 보유하고 있으며, 상속·증여세 최적화 전략 수립의 전문가입니다.',
    expertise: ['상속세', '증여세', '절세전략', '세무설계'],
  },
  jungGiHong: {
    id: 'jung-gi-hong',
    name: '정기홍',
    title: 'FO',
    company: '삼성패밀리오피스',
    bio: '삼성패밀리오피스 소속으로 고액자산가 자산관리와 투자 자문을 담당하고 있습니다.',
    expertise: ['자산관리', '투자자문', '패밀리오피스', '포트폴리오'],
  },
};

export const FEATURED_SPEAKERS: Speaker[] = [
  {
    id: 'samsung-life-director',
    name: '김재원',
    title: '상무',
    company: '삼성생명 패밀리오피스',
    bio: '삼성생명에서 25년간 자산관리 업무를 담당하며, 현재 패밀리오피스 사업부를 총괄하고 있습니다. VVIP 고객 대상 맞춤형 자산관리 전문가입니다.',
    expertise: ['자산관리', '포트폴리오', '패밀리오피스', 'VVIP서비스'],
  },
  {
    id: 'tax-specialist',
    name: '박세무',
    title: '세무사',
    company: '삼일회계법인',
    bio: '기업 및 개인 고액자산가 세무 전문가로 20년 이상의 경험을 보유하고 있으며, 상속·증여세 최적화 전략 수립의 권위자입니다.',
    expertise: ['상속세', '증여세', '절세전략', '세무설계'],
  },
  {
    id: 'succession-expert',
    name: '이승계',
    title: '대표변호사',
    company: '법무법인 광장',
    bio: '패밀리비즈니스 승계 전문 변호사로 대기업 오너 가문의 승계 설계를 담당하고 있으며, 가족법인 설립 및 운영 전문가입니다.',
    expertise: ['가업승계', '가족법인', '지배구조', 'M&A'],
  },
  {
    id: 'investment-director',
    name: '정투자',
    title: '투자본부장',
    company: '미래에셋대우',
    bio: '프라이빗뱅킹 부문에서 15년간 고액자산가 투자 자문을 담당하며, 대체투자 및 해외투자 전문가로 활동하고 있습니다.',
    expertise: ['대체투자', '해외투자', '프라이빗뱅킹', '자산배분'],
  },
];

export const UPCOMING_SEMINARS: Seminar[] = [
  {
    id: 'vip-asset-succession-tax-strategy-jan-2026',
    title: '자산승계와 절세전략 총정리',
    subtitle: 'VIP 고객초청 세미나',
    description:
      '급변하는 규제 환경과 복잡해지는 세무 정책 속에서 지속가능한 가업승계와 전략적 절세 플랜은 기업 경영자들의 핵심 과제가 되었습니다. 본 세미나는 초고액 자산가를 위한 맞춤형 솔루션을 제시하는 프리미엄 플랫폼으로 기획되었습니다.',
    speaker: {
      id: 'kim-sung-su-kim-hak-jin',
      name: '김성수 Family Officer, 김학진 전문교수',
      title: 'Family Officer / 전문교수',
      company: '삼성생명',
      bio: '삼성생명 패밀리오피스 분야의 전문가로 가업승계와 자산관리 전략을 제공합니다.',
      expertise: ['가업승계', '자산관리', '절세전략', '세무설계'],
    },
    date: '2026-01-05',
    time: '12:00',
    duration: '3시간 30분',
    location: {
      type: 'offline',
      venue: '삼성금융캠퍼스 B2 비전홀',
      address: '서울시 서초구 서초동 1641-10',
      capacity: 30,
    },
    category: 'succession',
    targetAudience: ['VVIP 고객', '기업 경영진', '초고액자산가'],
    capacity: 30,
    registeredCount: 0,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '세미나 당일 전액 환불',
    status: 'upcoming',
    tags: ['자산승계', '절세전략', '가업승계', 'VVIP'],
    registrationUrl: 'https://lu.ma/23jzgyy5',
    detailsUrl: 'https://lu.ma/23jzgyy5',
    agenda: [
      {
        time: '12:00',
        title: '오찬',
        duration: 60,
      },
      {
        time: '13:00',
        title: '1부 강의',
        description: '자산승계와 절세전략',
        speaker: '김성수 Family Officer',
        duration: 60,
      },
      {
        time: '14:10',
        title: '2부 강의',
        description: '심화 절세 전략',
        speaker: '김학진 전문교수',
        duration: 80,
      },
    ],
    specialInfo: {
      dresscode: 'Business Formal 또는 Smart Business',
      capacity: '한정된 좌석으로 사전 예약 필수',
      participationFee: '무료 (보증금 시스템 운영)',
      depositDetails: {
        amount: 50000,
        account: '카카오뱅크 3333-26-9880585 (예금주: 패밀리오피스)',
        deadline: '예약 신청 후 48시간 이내',
        refund: '세미나 당일 전액 환불',
      },
      verification: '세미나 품질 보장을 위한 비대면 고객 인증 절차',
      contactPhone: '0502-5550-8700',
      benefits: [
        '전문가 네트워크 접근: Big 4 회계법인 및 1급 금융기관 전문가진과의 직접 소통',
        '맞춤형 솔루션 제안: WIP(Wealth Management Integrated Planning) 시스템 기반 전략 수립',
        '후속 컨설팅 지원: 세미나 이후 지속적인 전문 자문 서비스',
      ],
    },
  },
  {
    id: 'vip-2026-tax-reform-ceo-strategy-jan-2026',
    title: "'26년 세제개편과 CEO 절세 전략",
    subtitle: 'VIP 고객 초청 세미나',
    description:
      '급변하는 규제 환경과 복잡해지는 세무 정책 속에서 지속가능한 가업승계와 전략적 절세 플랜은 기업 경영자들의 핵심 과제가 되었습니다. 본 세미나는 법인 CEO 및 자산가를 위한 맞춤형 솔루션을 제시하는 프리미엄 플랫폼으로 기획되었습니다.',
    speaker: {
      id: 'hwang-byung-hoon-yoo-jun-ho',
      name: '황병훈 세무전문가, 유준호 Family Officer',
      title: '세무전문가 / Family Officer',
      company: '삼성패밀리오피스',
      bio: '삼성패밀리오피스 소속 세무전문가로 고액자산가 세무 전문가로 15년 이상의 경험을 보유하고 있습니다.',
      expertise: ['세제개편', 'CEO절세', '상속세', '증여세'],
    },
    date: '2026-01-15',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '롯데호텔월드 3층 에메랄드룸',
      address: '서울시 송파구 올림픽로 240',
      capacity: 30,
    },
    category: 'taxation',
    targetAudience: ['VIP 고객', '법인 CEO', '자산가'],
    capacity: 30,
    registeredCount: 0,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '세미나 당일 전액 환불',
    status: 'upcoming',
    tags: ['26년세제개편', 'CEO절세', '법인전략', 'VIP'],
    registrationUrl: 'https://lu.ma/g0174snl',
    detailsUrl: 'https://lu.ma/g0174snl',
    agenda: [
      {
        time: '10:30',
        title: "'26년 세제개편과 CEO 절세 전략",
        description: '2026년 세제개편 내용과 CEO 맞춤 절세 전략',
        speaker: '황병훈 세무전문가, 유준호 Family Officer',
        duration: 120,
      },
      {
        time: '12:30',
        title: '호텔 오찬 및 개별 상담',
        description: '전문가와 함께하는 1:1 맞춤 상담 및 네트워킹',
        duration: 60,
      },
    ],
    specialInfo: {
      dresscode: 'Business Formal 또는 Smart Business',
      capacity: '한정된 좌석으로 사전 예약 필수',
      participationFee: '무료 (보증금 시스템 운영)',
      depositDetails: {
        amount: 50000,
        account: '카카오뱅크 3333-26-9880585 패밀리오피스',
        deadline: '예약 신청 후 48시간 이내',
        refund: '세미나 당일 전액 환불',
      },
      verification: '세미나 품질 보장을 위한 비대면 고객 인증 절차',
      contactPhone: '0502-5550-8700',
      parking: '무료 주차 지원',
      benefits: [
        '전문가 네트워크 접근: Big 4 회계법인 및 1급 금융기관 전문가진과의 직접 소통',
        '맞춤형 솔루션 제안: WIP(Wealth Management Integrated Planning) 시스템 기반 전략 수립',
        '후속 컨설팅 지원: 세미나 이후 지속적인 전문 자문 서비스',
      ],
    },
  },
  {
    id: 'vvip-2026-tax-law-asset-succession-jan-2026',
    title: '2026 개정 세법 및 상법 반영',
    subtitle: '구조변화를 통한 자산 승계 핵심 절세 전략',
    description:
      '급변하는 규제 환경과 복잡해지는 세무 정책 속에서 지속가능한 가업승계와 전략적 절세 플랜은 기업 경영자들의 핵심 과제가 되었습니다. 본 세미나는 초고액 자산가를 위한 맞춤형 솔루션을 제시하는 프리미엄 플랫폼으로 기획되었습니다.',
    speaker: {
      id: 'lee-sang-sun-2026',
      name: '이상선 박사',
      title: '박사',
      company: '삼성생명 컨설턴트',
      bio: '삼성생명에서 패밀리오피스 분야의 전문가로 20년 이상의 경험을 보유하고 있으며, 가업승계와 자산관리 전략의 권위자입니다.',
      expertise: ['세법개정', '상법', '구조변화', '자산승계'],
    },
    date: '2026-01-21',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '신라호텔 서울 3층 마로니에홀',
      address: '서울 중구 동호로 249',
      capacity: 30,
    },
    category: 'succession',
    targetAudience: ['VVIP 고객', '기업 경영진', '초고액자산가'],
    capacity: 30,
    registeredCount: 0,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '세미나 당일 전액 환불',
    status: 'upcoming',
    tags: ['2026세법개정', '상법반영', '구조변화', '자산승계', 'VVIP'],
    registrationUrl: 'https://lu.ma/uvzq29cf',
    detailsUrl: 'https://lu.ma/uvzq29cf',
    agenda: [
      {
        time: '10:30',
        title:
          '세법개정 및 상법 반영 구조변화를 통한 자산(가업) 승계 핵심 전략',
        description: '2026년 개정 세법과 상법을 반영한 구조변화 전략',
        speaker: '이상선 박사',
        duration: 120,
      },
      {
        time: '12:30',
        title: '호텔 오찬 및 개별 상담',
        description: '전문가와 함께하는 1:1 맞춤 상담 및 네트워킹',
        duration: 60,
      },
    ],
    specialInfo: {
      dresscode: 'Business Formal 또는 Smart Business',
      capacity: '한정된 좌석으로 사전 예약 필수',
      participationFee: '무료 (보증금 시스템 운영)',
      depositDetails: {
        amount: 50000,
        account: '카카오뱅크 3333-26-9880585',
        deadline: '예약 신청 후 48시간 이내',
        refund: '세미나 당일 전액 환불',
      },
      verification: '세미나 품질 보장을 위한 비대면 고객 인증 절차',
      contactPhone: '0502-5550-8700',
      parking: '무료 주차 지원',
      benefits: [
        '전문가 네트워크 접근: Big 4 회계법인 및 1급 금융기관 전문가진과의 직접 소통',
        '맞춤형 솔루션 제안: WIP(Wealth Management Integrated Planning) 시스템 기반 전략 수립',
        '후속 컨설팅 지원: 세미나 이후 지속적인 전문 자문 서비스',
      ],
    },
  },
  {
    id: 'vvip-asset-succession-tax-reform-2025',
    title: 'VVIP 고객초청 세미나',
    subtitle:
      '🎉🌟 자산 관리의 새로운 지평을 여는 VVIP 고객초청 세미나에 여러분을 초대합니다! 🌟🎉',
    description:
      '바쁘신 일정에도 시간을 내주셔서 성공적인 가업승계와 절세 플랜을 시작하는 첫걸음을 함께해 주시길 바랍니다. 본 세미나는 대표님의 사업과 가정에 실질적인 도움을 드릴 수 있는 특별한 자리로 준비되었습니다.',
    speaker: {
      id: 'lee-sang-sun-asset-succession',
      name: '이상선',
      title: '박사',
      company: '삼성생명 컨설턴트',
      bio: '삼성생명에서 패밀리오피스 분야의 전문가로 20년 이상의 경험을 보유하고 있으며, 가업승계와 자산관리 전략의 권위자입니다.',
      expertise: ['가업승계', '자산관리', '세법개정', '구조변화'],
    },
    date: '2025-10-21',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '그랜드하얏트 서울',
      address: '서울시 용산구 소월로 322 (2층 남산 I룸)',
      capacity: 30,
    },
    category: 'succession',
    targetAudience: ['VVIP 고객', '기업 경영진', '고액자산가'],
    capacity: 30,
    registeredCount: 0,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '세미나 당일 전액 환불',
    status: 'upcoming',
    tags: ['25년 세법개정', '구조변화', '자산승계', 'VVIP'],
    registrationUrl: 'https://luma.com/r23ksh5i',
    detailsUrl: 'https://luma.com/r23ksh5i',
    agenda: [
      {
        time: '10:30',
        title: '25년 세법개정 반영한 구조변화를 통한 자산 승계',
        description: '2025년 세법개정을 반영한 구조변화를 통한 자산 승계 전략',
        speaker: '이상선 박사',
        duration: 90,
      },
      {
        time: '12:30',
        title: '호텔 오찬 및 개별 상담',
        description: '전문가와 함께하는 1:1 맞춤 상담 및 네트워킹',
        duration: 60,
      },
    ],
    specialInfo: {
      dresscode: 'Business Formal 또는 Smart Business',
      capacity: '한정된 좌석으로 사전 예약 필수',
      participationFee: '무료 (보증금 시스템 운영)',
      depositDetails: {
        amount: 50000,
        account: '카카오뱅크 3333-26-9880585 (예금주: 패밀리오피스)',
        deadline: '예약 신청 후 48시간 이내',
        refund: '세미나 당일 전액 환불',
      },
      verification: '세미나 품질 보장을 위한 비대면 고객 인증 절차',
      contactPhone: '0502-5550-8700',
      benefits: [
        '전문가 네트워크 접근: Big 4 회계법인 및 1급 금융기관 전문가진과의 직접 소통',
        '맞춤형 솔루션 제안: WIP(Wealth Management Integrated Planning) 시스템 기반 전략 수립',
        '후속 컨설팅 지원: 세미나 이후 지속적인 전문 자문 서비스',
      ],
    },
  },
  {
    id: '2030-business-live-on-trend-korea-2026',
    title: '2030 Business Live ON',
    subtitle:
      '🎉🌟 경계가 사라지는 시대, 미래를 혁신하고 새로운 가능성을 창출하기 위한 기술의 진보 🌟🎉',
    description:
      '미래를 혁신하고 새로운 가능성을 창출하기 위한 기술의 진보 속에서 2025년 2030 Business Live ON과 함께 우리 앞에 예고된 세 가지 기술적 혁명을 알아보며, 이와 연계될 다른 산업 분야의 새로운 미래를 상상하고 꿈을 현실로 만드는 방법을 가늠해 보고자 합니다.',
    speaker: {
      id: 'kim-nan-do-professor',
      name: '김난도',
      title: '교수',
      company: '서울대학교 소비학과',
      bio: '서울대학교 생활과학대학 소비자학과 교수이자 소비트렌드분석센터 센터장입니다. 『트렌드 코리아』 시리즈의 저자로 매년 한국 사회의 소비트렌드를 예측하고 분석하는 대한민국 대표 트렌드 전문가입니다.',
      expertise: ['소비 트렌드', '미래 예측', '트렌드 분석', '소비자 행동'],
    },
    date: '2025-10-21',
    time: '07:30',
    duration: '1시간 30분',
    location: {
      type: 'hybrid',
      venue: '삼성금융캠퍼스 비전홀',
      address: '서울특별시 서초구 사임당로 23길 27 (지하2층)',
      capacity: 150,
      onlineLink: 'https://luma.com/y9p7jw4e',
    },
    category: 'technology',
    targetAudience: ['기업 임직원', '비즈니스 의사결정권자', 'CEO', '경영진'],
    capacity: 150,
    registeredCount: 45,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '행사 참석 시 전액 환불 / 불참 시 환불 불가',
    status: 'upcoming',
    tags: ['트렌드 코리아 2026', '기술 혁신', '미래 전략', '하이브리드'],
    registrationUrl: 'https://luma.com/y9p7jw4e',
    detailsUrl: 'https://luma.com/y9p7jw4e',
    agenda: [
      {
        time: '06:30',
        title: '조찬 서비스',
        description: '사전 신청자에 한해 조찬 제공',
        duration: 60,
      },
      {
        time: '07:30',
        title: '미리 보는 트렌드 코리아 2026',
        description:
          '2026년 핵심 비즈니스 동향과 기술 혁신 기반 신규 사업 기회',
        speaker: '김난도 교수',
        duration: 90,
      },
    ],
    specialInfo: {
      dresscode: 'Business Professional 또는 Smart Casual',
      capacity: '제한된 좌석으로 선착순 마감',
      participationFee: '무료 (보증금 시스템 운영)',
      depositDetails: {
        amount: 50000,
        account: '카카오뱅크 3333-26-9880585',
        deadline: '신청 후 48시간 이내',
        refund: '행사 참석 시 전액 환불 / 불참 시 환불 불가',
      },
      verification: '고품질 강연 환경 조성을 위한 비대면 참가자 인증',
      contactPhone: '0502-5550-8700',
      benefits: [
        '산업 트렌드 선제 파악: 2026년 핵심 비즈니스 동향 사전 습득',
        '전략적 인사이트 확보: 기술 혁신 기반 신규 사업 기회 발굴',
        '네트워크 확장: 동종업계 리더들과의 전략적 파트너십 구축',
      ],
      registrationDeadline: '10/14(화) 17시',
      requiredInfo: ['법인명/고객명', '고객연락처', '차량번호', '조찬여부'],
      transportation:
        '교대역 5번출구 앞 서초 03버스 탑승 후 삼성레포츠센터 정류장 하차 후 도보 3분',
      hybridOption:
        '온라인 라이브 스트리밍 제공 - 출장이나 일정상 현장 참석이 어려우신 분들을 위한 비대면 참가 가능',
    },
  },
  {
    id: 'vvip-critical-disaster-law-seminar',
    title: 'VVIP 고객초청 세미나',
    subtitle:
      '🎉🌟 자산 관리의 새로운 지평을 여는 VVIP 고객초청 세미나에 여러분을 초대합니다! 🌟🎉',
    description:
      '바쁘신 일정에도 시간을 내주셔서 성공적인 가업승계와 절세 플랜을 시작하는 첫걸음을 함께해 주시길 바랍니다. 본 세미나는 대표님의 사업과 가정에 실질적인 도움을 드릴 수 있는 특별한 자리로 준비되었습니다.',
    speaker: {
      id: 'yoo-sun-yong-labor-attorney',
      name: '유선용',
      title: '노무사',
      company: '패밀리오피스',
      bio: '중대재해처벌법 및 노동법 전문가로서 기업의 법적 리스크 관리와 대응 전략 수립의 권위자입니다. 대기업과 중견기업의 중대재해 예방 시스템 구축 및 법적 대응 컨설팅을 전문으로 합니다.',
      expertise: ['중대재해처벌법', '노동법', '리스크관리', '기업법무'],
    },
    date: '2025-10-17',
    time: '10:30',
    duration: '2시간',
    location: {
      type: 'offline',
      venue: '그랜드 하얏트 서울',
      address: '서울시 용산구 소월로 322 (2층 남산 III룸)',
      capacity: 30,
    },
    category: 'legal',
    targetAudience: ['VVIP 고객', '기업 경영진', '고액자산가'],
    capacity: 30,
    registeredCount: 3,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '세미나 참석 시 전액 환불',
    status: 'upcoming',
    tags: ['중대재해처벌법', '법인전략', '리스크관리', '컴플라이언스'],
    registrationUrl: 'https://lu.ma/18f21nx2',
    detailsUrl: 'https://lu.ma/18f21nx2',
    agenda: [
      {
        time: '10:30',
        title: '중대재해 발생기업 제재 강화에 따른 법인 전략',
        description: '중대재해처벌법 강화에 대응하는 기업의 법적 대응 전략',
        speaker: '유선용 노무사',
        duration: 120,
      },
      {
        time: '12:30',
        title: '호텔 오찬 및 개별 상담',
        description: '전문가와 함께하는 1:1 맞춤 상담 및 네트워킹',
        duration: 60,
      },
    ],
  },
  {
    id: 'vvip-asset-management-new-horizon',
    title: 'VVIP 고객초청 세미나',
    subtitle: '자산 관리의 새로운 지평',
    description:
      '성공적인 가업승계와 절세 플랜을 위한 법인 정관개정과 금융상품 활용 전략을 심도 있게 다룹니다. 대표님의 사업과 가정에 실질적인 도움을 드릴 수 있는 특별한 세미나입니다.',
    speaker: {
      id: 'familyoffice-expert',
      name: '패밀리오피스 전문가팀',
      title: '전문 컨설턴트',
      company: '패밀리오피스',
      bio: '가업승계와 자산관리 분야의 전문가로서 기업오너와 고액자산가를 위한 맞춤형 솔루션을 제공합니다.',
      expertise: ['가업승계', '절세전략', '법인정관', '금융상품'],
    },
    date: '2025-09-17',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '그랜드워커힐 서울',
      address: '서울시 광진구 워커힐로 177 (4층 아트홀)',
      capacity: 30,
    },
    category: 'succession',
    targetAudience: ['VVIP 고객', '기업 경영진', '고액자산가'],
    capacity: 30,
    registeredCount: 5,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '노쇼 방지를 위한 참가보증금 (세미나 참가 확인 시 즉시 환불)',
    status: 'upcoming',
    tags: ['법인정관', '금융상품', '가업승계', '절세전략'],
    registrationUrl: 'https://lu.ma/b6av2oyu',
    detailsUrl: 'https://lu.ma/b6av2oyu',
    agenda: [
      {
        time: '10:30',
        title: '등록 및 Welcome Coffee',
        duration: 30,
      },
      {
        time: '11:00',
        title: '법인 정관개정과 금융상품 활용 전략',
        description:
          '법인 정관개정을 통한 가업승계 준비와 최적의 금융상품 활용 방안',
        speaker: '패밀리오피스 전문가팀',
        duration: 90,
      },
      {
        time: '12:30',
        title: '호텔 오찬 및 개별 상담',
        description: '전문가와 함께하는 1:1 맞춤 상담 및 네트워킹',
        duration: 60,
      },
    ],
  },
  {
    id: 'vvip-seminar-grand-hyatt-july',
    title: 'VVIP 고객초청 세미나',
    subtitle: '미래를 준비하는 가업승계 전략',
    description:
      '차세대 경영진을 위한 체계적인 가업승계 전략과 자산관리 방안을 심도 있게 다룹니다. 업계 최고 전문가들과 함께하는 프리미엄 세미나에서 미래 경영 전략을 수립하세요.',
    speaker: SPEAKERS.leeSangSun,
    date: '2025-07-23',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '그랜드 하얏트 서울',
      address: '서울시 용산구 한강대로23길 322',
      capacity: 50,
    },
    category: 'succession',
    targetAudience: ['VVIP 고객', '기업 경영진', '차세대 리더'],
    capacity: 50,
    registeredCount: 12,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '노쇼 방지를 위한 참가보증금 (세미나 참가 확인 시 즉시 환불)',
    status: 'upcoming',
    tags: ['가업승계', 'VVIP', '경영전략', '차세대'],
    registrationUrl: 'https://lu.ma/k0lpxec5',
    detailsUrl: 'https://lu.ma/k0lpxec5',
    agenda: [
      {
        time: '10:30',
        title: '등록 및 Welcome Coffee',
        duration: 30,
      },
      {
        time: '11:00',
        title: '효과적인 가업승계 및 자산관리 전략',
        description: '성공적인 가업승계를 위한 체계적인 전략과 자산관리 방안',
        speaker: '이상선 박사',
        duration: 60,
      },
      {
        time: '12:00',
        title: '네트워킹 런치',
        duration: 60,
      },
      {
        time: '13:00',
        title: '개별 상담 및 Q&A 세션',
        description: '맞춤형 가업승계 전략 수립을 위한 개별 상담',
        duration: 30,
      },
    ],
  },
  {
    id: 'vvip-seminar-shilla-august',
    title: 'VVIP 고객초청 세미나',
    subtitle: '세무전문가와 패밀리오피스 전문가의 특별 강연',
    description:
      '황병훈 세무전문가와 정기홍 FO가 함께하는 특별 세미나입니다. 세무 설계와 패밀리오피스 운영에 대한 실무 중심의 강의를 통해 실질적인 도움을 드립니다.',
    speaker: SPEAKERS.hwangByungHoon,
    date: '2025-08-12',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '서울 신라호텔',
      address: '서울시 중구 동호로 249',
      capacity: 50,
    },
    category: 'taxation',
    targetAudience: ['VVIP 고객', '기업오너', '재무담당임원'],
    capacity: 50,
    registeredCount: 8,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '노쇼 방지를 위한 참가보증금 (세미나 참가 확인 시 즉시 환불)',
    status: 'upcoming',
    tags: ['세무설계', '패밀리오피스', 'VVIP', '절세전략'],
    registrationUrl: 'https://lu.ma/sd0gfmmn',
    detailsUrl: 'https://lu.ma/sd0gfmmn',
    agenda: [
      {
        time: '10:30',
        title: '등록 및 Welcome Coffee',
        duration: 30,
      },
      {
        time: '11:00',
        title: '25년 개정세법 및 CEO 자산관리 전략',
        description: '최신 세법 개정사항과 CEO를 위한 자산관리 전략',
        speaker: '황병훈 세무전문가',
        duration: 60,
      },
      {
        time: '12:00',
        title: '개정세법 주요내용 이해와 CEO 대응전략',
        description: '개정세법의 핵심 내용과 CEO들의 대응 방안',
        speaker: '정기홍 FO',
        duration: 45,
      },
      {
        time: '12:45',
        title: '네트워킹 런치',
        duration: 45,
      },
      {
        time: '13:30',
        title: '개별 상담 및 Q&A 세션',
        description: '맞춤형 세무 및 자산관리 전략 수립을 위한 개별 상담',
        duration: 30,
      },
    ],
  },
  {
    id: 'vvip-seminar-grand-hyatt-august',
    title: 'VVIP 고객초청 세미나',
    subtitle: '스마트한 세무 설계와 절세 전략',
    description:
      '최신 세법 변화에 대응하는 효과적인 세무 설계 방법과 절세 전략을 제시합니다. 상속·증여세 최적화와 기업 세무 리스크 관리 방안을 전문가와 함께 학습하세요.',
    speaker: SPEAKERS.leeSangSun,
    date: '2025-08-27',
    time: '10:30',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '그랜드 하얏트 서울',
      address: '서울시 용산구 한강대로23길 322',
      capacity: 50,
    },
    category: 'taxation',
    targetAudience: ['VVIP 고객', '기업오너', '재무담당임원'],
    capacity: 50,
    registeredCount: 15,
    price: 0,
    isPremium: true,
    deposit: 50000,
    depositNote: '노쇼 방지를 위한 참가보증금 (세미나 참가 확인 시 즉시 환불)',
    status: 'upcoming',
    tags: ['세무설계', '절세전략', 'VVIP', '상속증여'],
    registrationUrl: 'https://lu.ma/t83yj5i9',
    detailsUrl: 'https://lu.ma/t83yj5i9',
    agenda: [
      {
        time: '10:30',
        title: '등록 및 Welcome Coffee',
        duration: 30,
      },
      {
        time: '11:00',
        title: '효과적인 가업승계 및 자산관리 전략',
        description: '성공적인 가업승계를 위한 체계적인 전략과 자산관리 방안',
        speaker: '이상선 박사',
        duration: 60,
      },
      {
        time: '12:00',
        title: '네트워킹 런치',
        duration: 60,
      },
      {
        time: '13:00',
        title: '개별 상담 및 Q&A 세션',
        description: '맞춤형 세무 전략 수립을 위한 개별 상담',
        duration: 30,
      },
    ],
  },
  {
    id: 'samsung-life-asset-management-seoul',
    title: '삼성생명 자산관리 세미나',
    subtitle: '자산 관리의 새로운 지평',
    description:
      '🎉🌟 자산 관리의 새로운 지평을 여는 삼성생명 자산관리 세미나에 여러분을 초대합니다! 🌟🎉 바쁘신 일정에도 시간을 내주셔서 성공적인 가업승계와 절세 플랜을 시작하는 첫걸음을 함께해 주시길 바랍니다. 본 세미나는 대표님의 사업과 가정에 실질적인 도움을 드릴 수 있는 특별한 자리로 준비되었습니다.',
    speaker: {
      id: 'samsung-fp-team',
      name: '이임희 FP & 정재승 지점장',
      title: 'FP & 지점장',
      company: '서울FP센터 & 서울법인지역단',
      bio: '서울FP센터 소속 FP와 서울법인지역단 지점장으로 가업승계와 절세 전략 전문가입니다.',
      expertise: ['가업승계', '절세전략', '금융상품', '세제개편'],
    },
    date: '2025-09-20',
    time: '14:00',
    duration: '3시간',
    location: {
      type: 'offline',
      venue: '그랑서울타워II 14층 서울FP센터 세미나룸',
      address: '서울시 종로구 종로 33',
      capacity: 30,
    },
    category: 'taxation',
    targetAudience: ['기업 대표', '기업오너', '자산관리 관심자'],
    capacity: 30,
    registeredCount: 12,
    price: 0,
    isPremium: true,
    deposit: 30000,
    depositNote: '노쇼 방지를 위한 참가보증금 (세미나 참가 확인 시 즉시 환불)',
    status: 'upcoming',
    tags: ['2025년세제개편', '가업승계', '절세전략', '삼성생명'],
    registrationUrl: 'https://lu.ma/a6346rvz',
    detailsUrl: 'https://lu.ma/a6346rvz',
    agenda: [
      {
        time: '14:00',
        title: '2025년 세제 개편안 및 가업승계 전략',
        description: '금융상품을 활용한 절세 전략',
        speaker: '이임희 FP (서울FP센터) | 정재승 지점장 (서울법인지역단)',
        duration: 90,
      },
      {
        time: '15:30',
        title: '개별 상담',
        description: '맞춤형 가업승계 및 절세 전략 상담',
        duration: 90,
      },
    ],
  },
];

export const PAST_SEMINARS: Seminar[] = [
  {
    id: 'vvip-portfolio-2024',
    title: '2024년 VVIP 포트폴리오 성과 리뷰',
    subtitle: '삼성생명 패밀리오피스 연말 결산 세미나',
    description:
      '2024년 VVIP 고객 포트폴리오 성과를 분석하고 2025년 투자 전략 방향을 제시하는 연말 결산 세미나를 진행했습니다.',
    speaker: {
      id: 'samsung-review-team',
      name: '김재원',
      title: '상무',
      company: '삼성생명 패밀리오피스',
      bio: '삼성생명 패밀리오피스 사업부 총괄로 VVIP 고객 자산관리를 담당하고 있습니다.',
      expertise: ['자산관리', '포트폴리오', '성과분석', '투자전략'],
    },
    date: '2024-12-15',
    time: '15:00',
    duration: '2시간',
    location: {
      type: 'offline',
      venue: '삼성생명 본사 VIP룸',
      address: '서울시 중구 태평로2가 150',
    },
    category: 'finance',
    targetAudience: ['VVIP 고객', '자산가', '기업오너'],
    capacity: 30,
    registeredCount: 30,
    price: 0,
    isPremium: true,
    status: 'completed',
    tags: ['포트폴리오', '성과리뷰', '투자전략', 'VVIP'],
    agenda: [],
    videoUrl: 'https://cal.com/familyoffice/coffeechat',
    presentationUrl: 'https://cal.com/familyoffice/coffeechat',
  },
  {
    id: 'year-end-tax-2024',
    title: '2024년 연말정산 및 절세 전략',
    subtitle: '고액자산가를 위한 세무 최적화 방안',
    description:
      '연말정산 시즌을 맞아 고액자산가가 알아야 할 절세 전략과 2025년 세법 변화에 대한 대비책을 제시했습니다.',
    speaker: {
      id: 'tax-year-end',
      name: '박세무',
      title: '세무사',
      company: '삼일회계법인',
      bio: '고액자산가 세무 전문가로 상속·증여세 최적화 전략을 전문으로 합니다.',
      expertise: ['연말정산', '절세전략', '세무설계', '고액자산가'],
    },
    date: '2024-11-30',
    time: '14:00',
    duration: '2시간',
    location: {
      type: 'offline',
      venue: '삼성생명 본사 세미나룸',
      address: '서울시 중구 태평로2가 150',
    },
    category: 'taxation',
    targetAudience: ['VVIP 고객', '자산가', '기업오너'],
    capacity: 40,
    registeredCount: 40,
    price: 0,
    isPremium: true,
    status: 'completed',
    tags: ['연말정산', '절세전략', '세무설계', '고액자산가'],
    agenda: [],
    videoUrl: 'https://cal.com/familyoffice/coffeechat',
    presentationUrl: 'https://cal.com/familyoffice/coffeechat',
  },
];

export const SEMINAR_SERIES: SeminarSeries[] = [
  {
    id: 'vvip-quarterly',
    name: 'VVIP 분기별 세미나',
    description: 'VVIP 고객을 위한 분기별 특별 세미나 시리즈',
    seminars: UPCOMING_SEMINARS.filter(s => s.isPremium),
    totalSeminars: UPCOMING_SEMINARS.filter(s => s.isPremium).length,
    completedSeminars: PAST_SEMINARS.filter(s => s.isPremium).length,
    nextSeminar: UPCOMING_SEMINARS.find(
      s => s.isPremium && s.status === 'upcoming'
    ),
    registrationUrl: 'https://cal.com/familyoffice/coffeechat',
  },
  {
    id: 'tax-strategy',
    name: '세무 전략 시리즈',
    description: '고액자산가를 위한 세무 설계와 절세 전략 시리즈',
    seminars: [...UPCOMING_SEMINARS, ...PAST_SEMINARS].filter(
      s => s.category === 'taxation'
    ),
    totalSeminars: [...UPCOMING_SEMINARS, ...PAST_SEMINARS].filter(
      s => s.category === 'taxation'
    ).length,
    completedSeminars: PAST_SEMINARS.filter(s => s.category === 'taxation')
      .length,
    nextSeminar: UPCOMING_SEMINARS.find(
      s => s.category === 'taxation' && s.status === 'upcoming'
    ),
    registrationUrl: 'https://cal.com/familyoffice/coffeechat',
  },
];
