apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: familyoffice
type: Opaque
data:
  # echo -n "password" | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "familyoffice" | base64
  POSTGRES_DB: ZmFtaWx5b2ZmaWNl
