/**
 * SEO 페이지 매핑 정의
 */
export const SEO_PAGE_MAPPING: { [key: string]: string } = {
  // 법인세 결산 체크리스트
  '법인세 결산 체크리스트': '/corporate-tax-checklist',
  '결산 후 필수 점검': '/corporate-tax-checklist',
  '법인세 신고 체크리스트': '/corporate-tax-checklist#taxDeclaration',
  '재무제표 검토 체크리스트': '/corporate-tax-checklist#financialReview',
  '절세 전략 검토': '/corporate-tax-checklist#taxOptimization',
  '세무 컴플라이언스': '/corporate-tax-checklist#compliance',
  '차기년도 세무계획': '/corporate-tax-checklist#planning',
  '세무조정 검토': '/corporate-tax-checklist',
  '외부감사 대응': '/corporate-tax-checklist',

  // CEO 체크리스트 & 경영진단
  'CEO 체크리스트': '/ceo-checklist',
  경영진단: '/ceo-checklist',
  '기업 리스크 진단': '/ceo-checklist#risk',
  '가업승계 준비도 진단': '/ceo-checklist#succession',
  '중대재해처벌법 체크리스트': '/ceo-checklist#serious-accident',
  '재무 건전성 진단': '/ceo-checklist#financial',
  '성장전략 점검': '/ceo-checklist#growth',
  '개인자산 관리 진단': '/ceo-checklist#personal',

  // 절세 전략
  '절세의 미학': '/tax-strategy',
  '법인세 절세 전략': '/tax-strategy#corporate',
  '개인세 절세 전략': '/tax-strategy#personal',
  '승계세 절세 전략': '/tax-strategy#succession',
  '가지급금 절세 솔루션': '/tax-strategy#provisional-payment',
  '자기주식 절세 활용': '/tax-strategy#treasury-stock',

  // 가업승계 전략
  '패밀리오피스 전략적 가업승계': '/business-succession-strategy',
  '가업승계 전략': '/business-succession-strategy',
  '전략적 가업승계': '/business-succession-strategy',
  '승계 로드맵': '/business-succession-strategy',
  '5단계 승계': '/business-succession-strategy',
  '생전증여 승계': '/business-succession-strategy#gift',
  '상속승계 전략': '/business-succession-strategy#inheritance',
  '매각승계 방안': '/business-succession-strategy#sale',
  'MBO/MBI 승계': '/business-succession-strategy#mbo',
  '가족헌장 제정': '/business-succession-strategy#charter',
  가족경영협의회: '/business-succession-strategy#council',
  '패밀리오피스 설립': '/business-succession-strategy#office',
  '가족신탁 활용': '/business-succession-strategy#trust',
  '차세대 경영자 교육': '/business-succession-strategy',
  '승계 세무 최적화': '/business-succession-strategy',
  '경영권 안정화': '/business-succession-strategy',

  // 기업보험 & 금융솔루션
  '기업인증 컨설팅': '/business-certification',
  '단체보험 - 기업보장보험': '/group-insurance',
  '상속·증여 컨설팅': '/inheritance-gift',
  경영인정기보험: '/key-person-insurance',
  '정책자금 컨설팅': '/policy-funds',
  '중대재해처벌법 대응': '/serious-accident-law',
  '개인/법인 건강보험': '/health-insurance',
  '퇴직연금 컨설팅': '/retirement-pension',

  // 상속·증여세 가이드
  '상속·증여세 가이드': '/inheritance-gift-tax',
  상속세: '/inheritance-gift-tax',
  증여세: '/inheritance-gift-tax',
  상속세율: '/inheritance-gift-tax#inheritanceTax',
  증여세율: '/inheritance-gift-tax#giftTax',
  상속공제: '/inheritance-gift-tax#deductions',
  증여공제: '/inheritance-gift-tax#deductions',
  상속신고: '/inheritance-gift-tax#schedule',
  증여신고: '/inheritance-gift-tax#schedule',
  '국세청 상속세': '/inheritance-gift-tax',
  '국세청 증여세': '/inheritance-gift-tax',
  '세금상식 Q&A': '/inheritance-gift-tax#faq',
  '상속·증여 세금상식': '/inheritance-gift-tax',
  '상속세 절세 방법': '/inheritance-gift-tax#strategies',
  '증여세 절세 방법': '/inheritance-gift-tax#strategies',
  배우자공제: '/inheritance-gift-tax#deductions',
  자녀공제: '/inheritance-gift-tax#deductions',
  기초공제: '/inheritance-gift-tax#deductions',
  '상속세 계산': '/inheritance-gift-tax#calculator',
  '증여세 계산': '/inheritance-gift-tax#calculator',
  '상속세 신고기한': '/inheritance-gift-tax#schedule',
  '증여세 신고기한': '/inheritance-gift-tax#schedule',
  '상속재산 평가': '/inheritance-gift-tax',
  '증여재산 평가': '/inheritance-gift-tax',
  '상속세 납부방법': '/inheritance-gift-tax',
  '증여세 납부방법': '/inheritance-gift-tax',

  // FP센터 (Financial Planner Center)
  FP센터: '/fp-center',
  'Financial Planner': '/fp-center',
  재무설계: '/fp-center',
  '종합 재무설계': '/fp-center',
  '맞춤형 재무설계': '/fp-center',
  '자산관리 컨설팅': '/fp-center#investment',
  보험설계: '/fp-center#insurance',
  은퇴설계: '/fp-center#retirement',
  상속설계: '/fp-center#estate',
  '기업 금융컨설팅': '/fp-center#corporate',
  '삼성생명 FP센터': '/fp-center',
  '전문 FP': '/fp-center',
  재무진단: '/fp-center',
  자산배분: '/fp-center',
  '포트폴리오 관리': '/fp-center',
  '금융 전문가': '/fp-center',
  재무상담: '/fp-center',
  투자자문: '/fp-center',
  연금설계: '/fp-center',
  세무최적화: '/fp-center',
  리스크관리: '/fp-center',
  종합금융서비스: '/fp-center',

  // 기존 SEO 페이지 매핑
  '가업승계지원 제도 컨설팅': '/business-succession-strategy',
  가업주식증여특례: '/business-succession-strategy',
  가업상속공제: '/business-succession-strategy',
  '자녀법인 활용 전략': '/business-succession-strategy',
  창업자금증여특례: '/business-succession-strategy',
  '법인계약 세무회계': '/tax-strategy',
  '보험계약 상증세법 컨설팅': '/tax-strategy',
  '개인사업자 법인전환': '/tax-strategy',
  '경정청구 컨설팅': '/tax-strategy',
  '가지급금 컨설팅': '/inheritance-gift-tax',
  '자기주식 컨설팅': '/inheritance-gift-tax',
  '차명주식 컨설팅': '/inheritance-gift-tax',
  '법인종합재무 컨설팅': '/inheritance-gift-tax',
  '상환전환우선주 발행': '/investment-advisory',
  '중소기업 자금조달': '/investment-advisory',
  '비상장주식 가치평가': '/investment-advisory',
  '기업연구소 및 정책자금 컨설팅': '/policy-funds',
  '유상증자 컨설팅': '/asset-diversification',
  '스톡옵션 설계': '/asset-diversification',
  '법인 재무제표 분석': '/portfolio-optimization',
  '양수도거래 컨설팅': '/portfolio-optimization',
  '세법개정안 분석': '/portfolio-optimization',
  '세무조정계산서의 이해': '/portfolio-optimization',
  '고액자산가 자산관리': '/wealth-consulting',
  '부유층 자산관리 컨설팅': '/wealth-consulting',

  // 특허 & 창업지원
  '사업계획서 작성': '/patent-startup/business-plan',
  '창업 컨설팅': '/patent-startup/startup-consulting',
  '특허출원 지원': '/patent-startup/patent-application',
  '홈페이지 제작 지원': '/patent-startup/homepage-creation',

  // 인수합병 & 부실채권
  '부실채권 정리': '/ma-debt/debt-restructuring',
  '인수합병(M&A) 컨설팅': '/ma-debt/ma-consulting',
  '기업구조조정 지원': '/ma-debt/corporate-restructuring',

  // 인사노무 관리
  '인사노무 관리 가이드': '/hr-labor-management',
  '인사노무 체크리스트': '/hr-labor-management',
  '노동법 준수 관리': '/hr-labor-management#compliance',
  '채용 관리 시스템': '/hr-labor-management#recruitment',
  '근로시간 관리': '/hr-labor-management#workingTime',
  '임금 및 휴가 관리': '/hr-labor-management#wagesLeave',
  '안전보건 관리': '/hr-labor-management#safetyHealth',
  '노사관계 관리': '/hr-labor-management#laborRelations',
  '취업규칙 작성': '/hr-labor-management#employment-rules',
  '4대보험 관리': '/hr-labor-management#employment-insurance',
  '직장 내 괴롭힘 방지': '/hr-labor-management#workplace-harassment',

  // 재무·세무·노무 통합관리
  '가지급금 해결 방안': '/finance-tax-labor/provisional-payment',
  '경정청구 전문 서비스': '/finance-tax-labor/tax-refund',
  '고용지원금 활용 컨설팅': '/finance-tax-labor/employment-subsidy',

  // HR 지원 (기존 항목 유지)
  '중소기업 노무관리': '/hr-labor-management',

  // 종신보험 관련
  '개인/법인 종신보험': '/life-insurance',
  '법인종신보험 설계': '/life-insurance#corporate',
  '개인종신보험 설계': '/life-insurance#personal',
  '상속세 납부재원 종신보험': '/life-insurance#inheritance',
  '퇴직금 종신보험 활용': '/life-insurance#retirement',
};
