import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/services',
          '/strategic-partnership',
          '/market-entry',
          '/success-stories',
          '/about',
          '/contact',
          '/program',
          '/faq',
          '/seminar',
          '/blog',
          '/brand',
          '/recruit',
          '/api/docs',
          '/family-office-center',
          '/business-succession-strategy',
          '/insights',
          '/insights/market-intelligence',
          '/insights/weekly-brief',
          '/insights/resources',
          '/wealth-consulting',
          '/investment-advisory',
          '/tax-strategy',
          '/inheritance-gift-tax',
          '/hr-labor-management',
          '/business-certification',
          '/policy-funds',
          '/asset-diversification',
          '/portfolio-optimization',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/_next/',
          '/static/',
          '*.json',
          '*.xml',
          '/search',
          '/tmp/',
          '/node_modules/',
          '/api/webhooks/',
          '/api/admin/',
          '/api/sync-user',
          '/api/test-*',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/services',
          '/strategic-partnership',
          '/market-entry',
          '/success-stories',
          '/about',
          '/contact',
          '/program',
          '/faq',
          '/seminar',
          '/blog',
          '/brand',
          '/recruit',
          '/family-office-center',
          '/business-succession-strategy',
          '/insights',
          '/insights/market-intelligence',
          '/insights/weekly-brief',
          '/insights/resources',
          '/wealth-consulting',
          '/investment-advisory',
          '/tax-strategy',
          '/inheritance-gift-tax',
          '/hr-labor-management',
          '/business-certification',
          '/policy-funds',
          '/asset-diversification',
          '/portfolio-optimization',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
        crawlDelay: 0,
      },
      {
        userAgent: 'NaverBot',
        allow: [
          '/',
          '/services',
          '/strategic-partnership',
          '/market-entry',
          '/success-stories',
          '/about',
          '/contact',
          '/program',
          '/faq',
          '/seminar',
          '/blog',
          '/brand',
          '/recruit',
          '/family-office-center',
          '/business-succession-strategy',
          '/insights',
          '/insights/market-intelligence',
          '/insights/weekly-brief',
          '/insights/resources',
          '/wealth-consulting',
          '/investment-advisory',
          '/tax-strategy',
          '/inheritance-gift-tax',
          '/hr-labor-management',
          '/business-certification',
          '/policy-funds',
          '/asset-diversification',
          '/portfolio-optimization',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
        crawlDelay: 1,
      },
      {
        userAgent: 'Daumoa',
        allow: [
          '/',
          '/services',
          '/strategic-partnership',
          '/market-entry',
          '/success-stories',
          '/about',
          '/contact',
          '/program',
          '/faq',
          '/seminar',
          '/blog',
          '/brand',
          '/recruit',
          '/family-office-center',
          '/business-succession-strategy',
          '/insights',
          '/insights/market-intelligence',
          '/insights/weekly-brief',
          '/insights/resources',
          '/wealth-consulting',
          '/investment-advisory',
          '/tax-strategy',
          '/inheritance-gift-tax',
          '/hr-labor-management',
          '/business-certification',
          '/policy-funds',
          '/asset-diversification',
          '/portfolio-optimization',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/services',
          '/strategic-partnership',
          '/market-entry',
          '/success-stories',
          '/about',
          '/contact',
          '/program',
          '/faq',
          '/seminar',
          '/blog',
          '/brand',
          '/recruit',
          '/family-office-center',
          '/business-succession-strategy',
          '/insights',
          '/insights/market-intelligence',
          '/insights/weekly-brief',
          '/insights/resources',
          '/wealth-consulting',
          '/investment-advisory',
          '/tax-strategy',
          '/inheritance-gift-tax',
          '/hr-labor-management',
          '/business-certification',
          '/policy-funds',
          '/asset-diversification',
          '/portfolio-optimization',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
        crawlDelay: 1,
      },
    ],
    sitemap: 'https://familyoffices.vip/sitemap.xml',
    host: 'https://familyoffices.vip',
  };
}
